# Generated by Django 6.0.6 on 2026-07-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_backfill_operational_situations_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authauditlog',
            name='action',
            field=models.CharField(choices=[('login_success', 'Успешный вход'), ('login_failed', 'Неудачный вход'), ('logout', 'Выход'), ('register', 'Регистрация'), ('password_change', 'Смена пароля'), ('password_reset', 'Сброс пароля'), ('password_reset_requested', 'Запрос сброса пароля'), ('user_approved', 'Одобрение пользователя'), ('user_blocked', 'Блокировка пользователя')], max_length=30, verbose_name='Действие'),
        ),
    ]
