# Generated by Django 6.0.6

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='report_templates',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Автор',
                )),
            ],
            options={
                'verbose_name': 'Шаблон отчёта',
                'verbose_name_plural': 'Шаблоны отчётов',
                'ordering': ['-updated_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(
                    choices=[
                        ('countries', 'Страны'),
                        ('targets', 'Объекты'),
                        ('equipment', 'Вооружение и техника'),
                        ('events', 'События'),
                        ('situations', 'Оперативная обстановка'),
                        ('zones', 'Зоны действия'),
                        ('vulnerabilities', 'Уязвимости'),
                    ],
                    max_length=20,
                    verbose_name='Тип раздела',
                )),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок раздела')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='Фильтры выборки')),
                ('page_break_before', models.BooleanField(default=True, verbose_name='Разрыв страницы перед разделом')),
                ('template', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='sections',
                    to='reports.reporttemplate',
                    verbose_name='Шаблон',
                )),
            ],
            options={
                'verbose_name': 'Раздел отчёта',
                'verbose_name_plural': 'Разделы отчёта',
                'ordering': ['order', 'id'],
            },
        ),
    ]
