# Generated by Django 6.0.6 on 2026-07-23 18:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('analyzing', 'Анализ'), ('ready', 'Готово к применению'), ('applying', 'Применение'), ('applied', 'Применено'), ('cancelled', 'Отменено'), ('failed', 'Ошибка')], default='analyzing', max_length=16)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('bundle_path', models.CharField(blank=True, default='', max_length=500)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_exchange_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сессия импорта',
                'verbose_name_plural': 'Сессии импорта',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=64)),
                ('natural_key', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('unchanged', 'Без изменений'), ('conflict', 'Конфликт'), ('ambiguous', 'Неоднозначно')], max_length=16)),
                ('decision', models.CharField(choices=[('pending', 'Ожидает'), ('keep_local', 'Оставить локальное'), ('use_imported', 'Использовать импортированное')], default='pending', max_length=16)),
                ('local_snapshot', models.JSONField(blank=True, default=dict)),
                ('imported_snapshot', models.JSONField(blank=True, default=dict)),
                ('label', models.CharField(blank=True, default='', max_length=500)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='data_exchange.importsession')),
            ],
            options={
                'verbose_name': 'Элемент импорта',
                'verbose_name_plural': 'Элементы импорта',
                'indexes': [models.Index(fields=['session', 'entity_type'], name='data_exchan_session_2b5a72_idx'), models.Index(fields=['session', 'status'], name='data_exchan_session_27bed8_idx')],
            },
        ),
    ]
