# Generated by Django 6.0.6 on 2026-06-29 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_equipmentimage'),
        ('formular', '0040_rename_formular_te_target__a1f2c3_idx_formular_ta_target__849e33_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='equipmentimage',
            new_name='formular_eq_equipme_adec40_idx',
            old_name='formular_eq_equipme_idx',
        ),
        migrations.AlterField(
            model_name='equipmentparameterdefinition',
            name='action_type',
            field=models.ForeignKey(blank=True, help_text='Если задано, значение (км) отображается как зона на карте', null=True, on_delete=django.db.models.deletion.SET_NULL, to='formular.actiontype', verbose_name='Тип зоны действия'),
        ),
    ]
