# Generated by Django 6.0.6 on 2026-07-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_equipmentparameterdefinition_zone_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentparameterdefinition',
            name='zone_color',
            field=models.CharField(blank=True, help_text='Пусто — наследуется из типа действия', max_length=7, null=True, verbose_name='Цвет зоны'),
        ),
    ]
