# Generated by Django 5.2.5 on 2025-11-21 03:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Страна')),
                ('color', models.CharField(choices=[('blue', 'синий'), ('green', 'зеленый'), ('red', 'красный'), ('yellow', 'желтый')], default='blue', max_length=20, verbose_name='Цвет маркера')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('title', models.CharField(max_length=250, verbose_name='Наименование объекта разведки')),
                ('label', models.CharField(blank=True, max_length=250, null=True, verbose_name='Метка')),
                ('lat', models.FloatField(verbose_name='Долгота')),
                ('lng', models.FloatField(verbose_name='Широта')),
            ],
            options={
                'verbose_name': 'Объект разведки',
                'verbose_name_plural': 'Объекты разведки',
                'indexes': [models.Index(fields=['title'], name='formular_ta_title_49a178_idx'), models.Index(fields=['label'], name='formular_ta_label_33d8c4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Formular',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formular.target', verbose_name='Объект разведки')),
            ],
        ),
    ]
