# Generated by Django 5.2.5 on 2025-11-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страны'},
        ),
        migrations.AddField(
            model_name='country',
            name='title_short',
            field=models.CharField(default='РУ', max_length=10, verbose_name='Сокращение'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['title'], name='formular_co_title_6a7c1a_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['title_short'], name='formular_co_title_s_190a02_idx'),
        ),
    ]
