# Generated by Django 5.2.5 on 2025-11-21 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0002_alter_country_options_country_title_short_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AddField(
            model_name='target',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contries', to='formular.country', verbose_name='Страна'),
            preserve_default=False,
        ),
    ]
