# Generated by Django 5.2.5 on 2025-12-01 06:33

import django.db.models.deletion
import formular.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0003_alter_country_options_target_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('path', models.FileField(help_text='Загрузка маркеров в хранилище', upload_to='markers', validators=[formular.validators.validate_svg], verbose_name='SVG-файл маркера')),
                ('top', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Оступ сверху для строки подписи, %')),
                ('width', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Шширина строки подписи, %')),
                ('height', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Высота строки подписиб %')),
                ('is_flag', models.BooleanField(default=True, verbose_name='Является ди флагом')),
            ],
            options={
                'verbose_name': 'Маркер',
                'verbose_name_plural': 'Маркеры',
                'indexes': [models.Index(fields=['title'], name='formular_ma_title_97a808_idx')],
            },
        ),
        migrations.AddField(
            model_name='target',
            name='marker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='markers', to='formular.marker', verbose_name='Маркер'),
        ),
    ]
