# Generated by Django 5.2.5 on 2025-12-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0004_marker_target_marker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='height',
            field=models.IntegerField(max_length=3, verbose_name='Высота строки подписиб %'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='top',
            field=models.IntegerField(max_length=3, verbose_name='Оступ сверху для строки подписи, %'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='width',
            field=models.IntegerField(max_length=3, verbose_name='Ширина строки подписи, %'),
        ),
    ]
