# Generated by Django 5.2.5 on 2025-12-02 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0005_alter_marker_height_alter_marker_top_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='order',
            field=models.SmallIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='height',
            field=models.IntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100, message='Значение не может превышать 100'), django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным')], verbose_name='Высота строки подписиб %'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='is_flag',
            field=models.BooleanField(default=True, verbose_name='Является ли флагом'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='top',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100, message='Значение не может превышать 100'), django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным')], verbose_name='Оступ сверху для строки подписи, %'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='width',
            field=models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100, message='Значение не может превышать 100'), django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным')], verbose_name='Ширина строки подписи, %'),
        ),
    ]
