# Generated by Django 5.2.5 on 2025-12-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0006_marker_order_alter_marker_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Порядок'),
        ),
    ]
