# Generated by Django 5.2.5 on 2025-12-03 05:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0007_alter_marker_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='scale',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2, validators=[django.core.validators.MaxValueValidator(1, message='Значение не иожет быть больше 1'), django.core.validators.MinValueValidator(0.1, message='Значение не может быть меньше 0.1')], verbose_name='Масштаб флажка'),
        ),
    ]
