# Generated by Django 6.0.1 on 2026-01-22 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0008_marker_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='height',
            field=models.IntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100, message='Значение не может превышать 100'), django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным')], verbose_name='Высота строки подписи, %'),
        ),
    ]
