# Generated by Django 6.0.1 on 2026-01-27 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0009_alter_marker_height'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='target',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.AddField(
            model_name='target',
            name='action_radius',
            field=models.FloatField(default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0.0, message='Значение не может быть отрицательным')], verbose_name='Радиус действия, км'),
        ),
    ]
