# Generated by Django 6.0.1 on 2026-01-28 10:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0010_alter_target_options_target_action_radius'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Тип действия')),
            ],
            options={
                'verbose_name': 'Тип действия',
                'verbose_name_plural': 'Типы действий',
                'indexes': [models.Index(fields=['title'], name='formular_ac_title_36b480_idx')],
            },
        ),
        migrations.CreateModel(
            name='TargetAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='Значение не может быть отрицательным')], verbose_name='Радиус действия, км')),
                ('action_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formular.actiontype', verbose_name='Тип действия')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='formular.target', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Радиус действия объекта',
                'verbose_name_plural': 'Радиус действия объектов',
            },
        ),
    ]
