# Generated by Django 6.0.1 on 2026-01-28 10:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0011_actiontype_targetaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetaction',
            name='action_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='formular.actiontype', verbose_name='Тип действия'),
        ),
        migrations.AlterField(
            model_name='targetaction',
            name='radius',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0, message='Значение не может быть отрицательным')], verbose_name='Радиус действия, км'),
        ),
    ]
