# Generated by Django 6.0.1 on 2026-01-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0012_alter_targetaction_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontype',
            name='animation',
            field=models.CharField(choices=[('gradient', 'Градиент'), ('radar', 'Радар'), ('wave', 'Волна'), ('pulse', 'Пульсация'), ('rings', 'Кольца'), ('sector', 'Сектор'), ('alert', 'Тревога'), ('dashed_rotate', 'Вращающийся пунктир')], default='wave', max_length=20, verbose_name='Анимация действия'),
        ),
    ]
