# Generated by Django 6.0.1 on 2026-01-28 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0013_actiontype_animation'),
    ]

    operations = [
        migrations.AddField(
            model_name='formular',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание пункта'),
        ),
        migrations.CreateModel(
            name='CountrySections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название раздела')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Раздел информации по стране',
                'verbose_name_plural': 'Разделы информации по странам',
                'indexes': [models.Index(fields=['title'], name='formular_co_title_29c9c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='FormularSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название раздела')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Раздел формуляра',
                'verbose_name_plural': 'Разделы формуляра',
                'indexes': [models.Index(fields=['title'], name='formular_fo_title_f3bd8a_idx')],
            },
        ),
        migrations.AddField(
            model_name='formular',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='formular_sections', to='formular.formularsections', verbose_name='Раздел формуляра'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CountryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержание')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_infos', to='formular.country', verbose_name='Страна')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_sections', to='formular.countrysections', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Информация по стране',
                'verbose_name_plural': 'Информация по странам',
                'indexes': [models.Index(fields=['country'], name='formular_co_country_e326db_idx'), models.Index(fields=['section'], name='formular_co_section_a2c8a3_idx')],
            },
        ),
    ]
