# Generated by Django 6.0.1 on 2026-01-28 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0014_formular_content_countrysections_formularsections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrysections',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='formular.countrysections', verbose_name='Родительский раздел'),
        ),
    ]
