# Generated by Django 6.0.1 on 2026-01-28 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0015_countrysections_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularsections',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='formular.formularsections', verbose_name='Родительский раздел'),
        ),
    ]
