# Generated by Django 6.0.1 on 2026-01-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0016_formularsections_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formular',
            options={'verbose_name': 'Пункт формуляра', 'verbose_name_plural': 'Пункты формуляра'},
        ),
        migrations.AddField(
            model_name='countrysections',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыть раздел'),
        ),
        migrations.AddField(
            model_name='formularsections',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыть раздел в формуляре'),
        ),
        migrations.AddIndex(
            model_name='formular',
            index=models.Index(fields=['target'], name='formular_fo_target__133996_idx'),
        ),
        migrations.AddIndex(
            model_name='formular',
            index=models.Index(fields=['section'], name='formular_fo_section_4a3e20_idx'),
        ),
    ]
