# Generated by Django 6.0.1 on 2026-01-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0017_alter_formular_options_countrysections_is_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='iso_code',
            field=models.CharField(default='UZB', max_length=3, verbose_name='ISO код страны'),
            preserve_default=False,
        ),
    ]
