# Generated by Django 6.0.1 on 2026-02-03 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0010_event'),
        ('formular', '0018_country_iso_code'),
    ]

    operations = [
    ]
