# Generated by Django 6.0.1 on 2026-02-04 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0019_merge_0010_event_0018_country_iso_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Тип объекта разведки')),
            ],
            options={
                'verbose_name': 'Тип объекта разведки',
                'verbose_name_plural': 'Типы объектов разведки',
            },
        ),
        migrations.AlterModelOptions(
            name='marker',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Маркер', 'verbose_name_plural': 'Маркеры'},
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='formular_ev_date_st_44778e_idx',
            old_name='formular_ev_date_st_6b5b3a_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='formular_ev_date_en_5ce2db_idx',
            old_name='formular_ev_date_en_2c0b1d_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='formular_ev_country_9e00eb_idx',
            old_name='formular_ev_country_86ac4b_idx',
        ),
        migrations.AddIndex(
            model_name='targettype',
            index=models.Index(fields=['title'], name='formular_ta_title_d9eaa5_idx'),
        ),
        migrations.AddField(
            model_name='target',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_types', to='formular.targettype', verbose_name='Тип объекта разведки'),
        ),
    ]
