# Generated by Django 6.0.1 on 2026-02-04 17:46

import django.db.models.deletion
import formular.validators
from django.db import migrations, models


def copy_markers_to_event_markers(apps, schema_editor):
    Marker = apps.get_model('formular', 'Marker')
    EventMarker = apps.get_model('formular', 'EventMarker')

    for marker in Marker.objects.all():
        EventMarker.objects.get_or_create(
            id=marker.id,
            defaults={
                'title': marker.title,
                'path': marker.path
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0021_eventtype_event_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('path', models.FileField(help_text='Загрузка маркеров событий в хранилище', upload_to='event_markers', validators=[formular.validators.validate_svg], verbose_name='SVG-файл маркера события')),
            ],
        ),
        migrations.RunPython(copy_markers_to_event_markers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='event',
            name='marker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='formular.eventmarker', verbose_name='Маркер события'),
        ),
    ]
