# Generated by Django 6.0.1 on 2026-02-05 11:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0022_eventmarker_alter_event_marker'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='formular_attachments', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formular_attachments', to='formular.formularsections', verbose_name='Раздел формуляра')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formular_attachments', to='formular.target', verbose_name='Объект разведки')),
            ],
            options={
                'verbose_name': 'Изображение формуляра',
                'verbose_name_plural': 'Изображения формуляра',
                'indexes': [models.Index(fields=['target'], name='formular_fo_target__fb5550_idx'), models.Index(fields=['section'], name='formular_fo_section_b441f1_idx')],
            },
        ),
    ]
