# Generated by Django 6.0.1 on 2026-02-05 12:00

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0023_formularattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='country_attachments', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_attachments', to='formular.country', verbose_name='Страна')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_attachments', to='formular.countrysections', verbose_name='Раздел информации по стране')),
            ],
            options={
                'verbose_name': 'Изображение информации по стране',
                'verbose_name_plural': 'Изображения информации по стране',
                'indexes': [
                    models.Index(fields=['country'], name='formular_co_country_3d3d1e_idx'),
                    models.Index(fields=['section'], name='formular_co_section_0c3555_idx'),
                ],
            },
        ),
    ]
