# Generated by Django 6.0.1 on 2026-02-05 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0024_countryattachment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='countryattachment',
            new_name='formular_co_country_1da29a_idx',
            old_name='formular_co_country_3d3d1e_idx',
        ),
        migrations.RenameIndex(
            model_name='countryattachment',
            new_name='formular_co_section_330de3_idx',
            old_name='formular_co_section_0c3555_idx',
        ),
    ]
