# Generated by Django 6.0.1 on 2026-02-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0024_countryattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(default='#2f80ed', max_length=7, verbose_name='Цвет события'),
        ),
    ]
