# Generated by Django 6.0.1 on 2026-02-05 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0025_event_color'),
        ('formular', '0025_rename_formular_co_country_3d3d1e_idx_formular_co_country_1da29a_idx_and_more'),
    ]

    operations = [
    ]
