# Generated by Django 5.2.5 on 2026-02-27 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0026_merge_20260205_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrysections',
            options={'ordering': ['order'], 'verbose_name': 'Раздел информации по стране', 'verbose_name_plural': 'Разделы информации по странам'},
        ),
        migrations.AlterModelOptions(
            name='eventmarker',
            options={'verbose_name': 'Маркер события', 'verbose_name_plural': 'Маркеры событий'},
        ),
        migrations.AlterModelOptions(
            name='formularsections',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Раздел формуляра', 'verbose_name_plural': 'Разделы формуляра'},
        ),
        migrations.AlterField(
            model_name='country',
            name='color',
            field=models.CharField(choices=[('blue', 'синий'), ('green', 'зеленый'), ('red', 'красный'), ('yellow', 'желтый'), ('marine', 'морской')], default='blue', max_length=20, verbose_name='Цвет маркера'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='top',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100, message='Значение не может превышать 100'), django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным')], verbose_name='Оступ сверху для строки подписи, %'),
        ),
        migrations.AddIndex(
            model_name='eventmarker',
            index=models.Index(fields=['title'], name='formular_ev_title_d724fb_idx'),
        ),
    ]
