# Generated by Django 6.0.6 on 2026-06-17 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0027_alter_countrysections_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='formular.target', verbose_name='Вышестоящий объект'),
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['parent'], name='formular_ta_parent__29b3fb_idx'),
        ),
    ]
