# Generated by Django 6.0.6 on 2026-06-18 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0028_target_parent_target_formular_ta_parent__29b3fb_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilitaryBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Вид / род войск')),
                ('countries', models.ManyToManyField(blank=True, help_text='Если список пуст — вид/род войск применим ко всем странам', related_name='applicable_military_branches', to='formular.country', verbose_name='Применимо к странам')),
            ],
            options={
                'verbose_name': 'Вид / род войск',
                'verbose_name_plural': 'Виды и рода войск',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='target',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targets', to='formular.militarybranch', verbose_name='Вид / род войск'),
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['branch'], name='formular_ta_branch__22d6ec_idx'),
        ),
        migrations.AddIndex(
            model_name='militarybranch',
            index=models.Index(fields=['title'], name='formular_mi_title_afd6d9_idx'),
        ),
    ]
