# Generated by Django 6.0.6 on 2026-06-21 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0030_targettype_countries_remove_militarybranch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='targettype',
            options={'ordering': ['title'], 'verbose_name': 'Тип объекта разведки', 'verbose_name_plural': 'Типы объектов разведки'},
        ),
        migrations.AlterField(
            model_name='target',
            name='action_radius',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0.0, message='Значение не может быть отрицательным')], verbose_name='Радиус действия, км'),
        ),
    ]
