# Generated by Django 6.0.6 on 2026-06-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0032_remove_target_branch'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='target',
            name='formular_ta_branch__22d6ec_idx',
        ),
    ]
