# Generated by Django 6.0.6 on 2026-06-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0034_actiontype_color_line_type_remove_animation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiontype',
            name='line_type',
            field=models.CharField(choices=[('solid', 'Сплошная линия'), ('dashed', 'Пунктирная линия'), ('dash_dot', 'Тире точка'), ('dash_x', 'Тире крест')], default='solid', max_length=20, verbose_name='Тип линии'),
        ),
    ]
