# Generated by Django 6.0.6 on 2026-07-11 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0048_operationalsituationrevision_situation_time'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='operationalsituationrevision',
            new_name='formular_op_situati_2cbc23_idx',
            old_name='formular_os_sitdate_idx',
        ),
        migrations.RenameIndex(
            model_name='operationalsituationrevision',
            new_name='formular_op_created_2778e7_idx',
            old_name='formular_os_created_idx',
        ),
        migrations.RenameIndex(
            model_name='person',
            new_name='formular_pe_target__dfe900_idx',
            old_name='formular_pe_target__b3c4d5_idx',
        ),
        migrations.RenameIndex(
            model_name='personattachment',
            new_name='formular_pe_person__ee4b2a_idx',
            old_name='formular_pe_person__2e3f4a_idx',
        ),
        migrations.RenameIndex(
            model_name='personattachment',
            new_name='formular_pe_section_1acc16_idx',
            old_name='formular_pe_section_5b6c7d_idx',
        ),
        migrations.RenameIndex(
            model_name='personinfo',
            new_name='formular_pe_person__ee1fd4_idx',
            old_name='formular_pe_person__e6f7a8_idx',
        ),
        migrations.RenameIndex(
            model_name='personinfo',
            new_name='formular_pe_section_a19626_idx',
            old_name='formular_pe_section_9b0c1d_idx',
        ),
        migrations.RenameIndex(
            model_name='personphoto',
            new_name='formular_pe_person__40b85d_idx',
            old_name='formular_pe_person__a8f4c2_idx',
        ),
        migrations.RenameIndex(
            model_name='personrelation',
            new_name='formular_pe_person__dcbb73_idx',
            old_name='formular_pe_person__8e9f0a_idx',
        ),
        migrations.RenameIndex(
            model_name='personrelation',
            new_name='formular_pe_person__aaccc2_idx',
            old_name='formular_pe_person__1b2c3d_idx',
        ),
        migrations.RenameIndex(
            model_name='personsections',
            new_name='formular_pe_title_176629_idx',
            old_name='formular_pe_title_8a1f2c_idx',
        ),
    ]
