# Generated by Django 6.0.6 on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0066_demo_stage_cue'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoscenariostep',
            name='wait_for_click',
            field=models.BooleanField(default=False, verbose_name='Переход к следующему шагу по щелчку'),
        ),
    ]
