# Generated by Django 6.0.6 on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0067_demoscenariostep_wait_for_click'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='demoscenariostage',
            new_name='formular_de_scenari_0ee30f_idx',
            old_name='formular_de_scenari_stage_ord_idx',
        ),
        migrations.RenameIndex(
            model_name='demoscenariostep',
            new_name='formular_de_stage_i_4f317f_idx',
            old_name='formular_de_stage_order_idx',
        ),
        migrations.AlterField(
            model_name='demoscenario',
            name='tableau',
            field=models.JSONField(blank=True, default=dict, help_text='blocks[{id,title,width,height,elements}], presets[{id,title,cue,variant,stage_id,tilt,gallery,placements,arrows}], active_preset_id', verbose_name='Художественный режим (JSON)'),
        ),
        migrations.AlterField(
            model_name='demoscenariostep',
            name='selection',
            field=models.JSONField(blank=True, default=dict, help_text='target_ids, event_ids, situation_ids, zone_leaves, overlay_layer_ids, country_isos, mosaic_action', verbose_name='Выбранные элементы (JSON)'),
        ),
        migrations.AlterField(
            model_name='demoscenariostep',
            name='tool',
            field=models.CharField(choices=[('camera', 'Камера'), ('objects', 'Объекты'), ('events', 'События'), ('zones', 'Зоны действия'), ('inundation', 'Зоны затопления'), ('situations', 'Оперативная обстановка'), ('layers', 'Слои карты'), ('formular', 'Формуляр объекта'), ('country', 'Справка по стране'), ('text', 'Текст на карте'), ('mosaic', 'Мультиэкран')], default='camera', max_length=20, verbose_name='Инструмент'),
        ),
    ]
