# Generated by Django 6.0.6 on 2026-09-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('formular', '0068_rename_formular_de_scenari_stage_ord_idx_formular_de_scenari_0ee30f_idx_and_more')]

    operations = [
        migrations.AddField(
            model_name='demoscenariostage', name='duration_ms',
            field=models.PositiveIntegerField(default=0, help_text='0 — длительность определяется шагами этапа.', verbose_name='Длительность этапа, мс'),
        ),
    ]
