export const ENTITY_LABELS = {
  marker_color_palettes: 'Палитры маркеров',
  markers: 'Маркеры',
  event_markers: 'Маркеры событий',
  action_types: 'Типы зон',
  event_types: 'Типы событий',
  target_types: 'Типы объектов',
  country_sections: 'Разделы досье',
  formular_sections: 'Разделы формуляра',
  person_sections: 'Разделы персоналий',
  relation_types: 'Типы связей',
  equipment_categories: 'Категории техники',
  units_of_measure: 'Единицы измерения',
  equipment_parameter_definitions: 'Параметры техники',
  countries: 'Страны',
  equipment: 'Техника',
  country_infos: 'Досье страны',
  country_attachments: 'Вложения досье',
  targets: 'Объекты',
  formulars: 'Формуляр',
  formular_attachments: 'Вложения формуляра',
  target_vulnerabilities: 'Уязвимости',
  events: 'События',
  persons: 'Персоналии',
  person_infos: 'Данные лиц',
  person_attachments: 'Вложения лиц',
  person_photos: 'Фото лиц',
  person_relations: 'Связи лиц',
};
